name: Contract CI
on:
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant permissions
        run: chmod +x gradlew
      - name: Build
        run: gradle build
      - name: Publish
        run: gradle publish
        env:
          GITHUB_USER: ${{ secrets.CI_USER }}
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
